# -*- coding: utf-8 -*-
# @Author  : 柑云宫音. [ ShoreKeep ]
# @Function : 显示战斗数据板

# 中文
#红#
execute as @a[scores={A1T12P=1},tag=inf,tag=语言] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       起床战争\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=语言事件]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§c红§r§f 红队: "},{"selector":"@e[tag=rtbeds]"},{"text":"§7 (你)\n§9蓝§r§f 蓝队: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§e黄§r§f 黄队: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§a绿§r§f 绿队: "},{"selector":"@e[tag=gtbeds]"},{"text":"\n\n§f击杀数: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§f最终击杀数: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§f破坏床数: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}
#蓝#
execute as @a[scores={A1T12P=2},tag=inf,tag=语言] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       起床战争\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=语言事件]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§c红§r§f 红队: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9蓝§r§f 蓝队: "},{"selector":"@e[tag=btbeds]"},{"text":"§7 (你)\n§e黄§r§f 黄队: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§a绿§r§f 绿队: "},{"selector":"@e[tag=gtbeds]"},{"text":"\n\n§f击杀数: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§f最终击杀数: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§f破坏床数: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}
#黄#
execute as @a[scores={A1T12P=4},tag=inf,tag=语言] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       起床战争\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=语言事件]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§c红§r§f 红队: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9蓝§r§f 蓝队: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§e黄§r§f 黄队: "},{"selector":"@e[tag=ytbeds]"},{"text":"§7 (你)\n§a绿§r§f 绿队: "},{"selector":"@e[tag=gtbeds]"},{"text":"\n\n§f击杀数: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§f最终击杀数: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§f破坏床数: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}
#绿#
execute as @a[scores={A1T12P=3},tag=inf,tag=语言] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       起床战争\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=语言事件]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§c红§r§f 红队: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9蓝§r§f 蓝队: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§e黄§r§f 黄队: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§a绿§r§f 绿队: "},{"selector":"@e[tag=gtbeds]"},{"text":"§7 (你)\n\n§f击杀数: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§f最终击杀数: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§f破坏床数: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}

# language
#红#
execute as @a[scores={A1T12P=1},tag=inf,tag=language] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       BED WARS\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=languageevent]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§cR§r§f Red: "},{"selector":"@e[tag=rtbeds]"},{"text":"§7 (you)\n§9B§r§f Blue: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§eY§r§f Yellow: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§aG§r§f Green: "},{"selector":"@e[tag=gtbeds]"},{"text":"\n\n§fKill: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§fFinal Kill: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§fBed Broken: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}
#蓝#
execute as @a[scores={A1T12P=2},tag=inf,tag=language] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       BED WARS\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=languageevent]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§cR§r§f Red: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9B§r§f Blue: "},{"selector":"@e[tag=btbeds]"},{"text":"§7 (you)\n§eY§r§f Yellow: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§aG§r§f Green: "},{"selector":"@e[tag=gtbeds]"},{"text":"\n\n§fKill: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§fFinal Kill: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§fBed Broken: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}
#黄#
execute as @a[scores={A1T12P=4},tag=inf,tag=language] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       BED WARS\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=languageevent]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§cR§r§f Red: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9B§r§f Blue: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§eY§r§f Yellow: "},{"selector":"@e[tag=ytbeds]"},{"text":"§7 (you)\n§aG§r§f Green: "},{"selector":"@e[tag=gtbeds]"},{"text":"\n\n§fKill: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§fFinal Kill: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§fBed Broken: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}
#绿#
execute as @a[scores={A1T12P=3},tag=inf,tag=language] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       BED WARS\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=languageevent]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§cR§r§f Red: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9B§r§f Blue: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§eY§r§f Yellow: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§aG§r§f Green: "},{"selector":"@e[tag=gtbeds]"},{"text":"§7 (you)\n\n§fKill: §a"},{"score":{"name":"@s","objective":"O3G30Q"}},{"text":"\n§fFinal Kill: §a"},{"score":{"name":"@s","objective":"G2L41J"}},{"text":"\n§fBed Broken: §a"},{"score":{"name":"@s","objective":"R4DO6T"}},{"text":"\n\n§emc.163.com/cnpixel"}]}



#场外但观战
execute as @a[m=spectator,tag=语言,tag=观战,tag=!inf] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       起床战争\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=语言事件]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§c红§r§f 红队: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9蓝§r§f 蓝队: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§e黄§r§f 黄队: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§a绿§r§f 绿队: "},{"selector":"@e[tag=gtbeds]"},{"text":"§7\n\n§f你现在是一名旁观者\n\n§emc.163.com/cnpixel"}]}

execute as @a[m=spectator,tag=language,tag=观战,tag=!inf] at @s run titleraw @s actionbar {"rawtext":[{"text":"§e§l       BED WARS\n"},{"text":"§r§726/3/3 v1.66[Beta]\n\n§f"},{"selector":"@e[tag=languageevent]"},{"text":"§f - §a"},{"score":{"name":"sjm2","objective":"D9T95M"}},{"score":{"name":"sjm1","objective":"D9T95M"}},{"text":":"},{"score":{"name":"sjs2","objective":"D9T95M"}},{"score":{"name":"sjs1","objective":"D9T95M"}},{"text":"\n\n§cR§r§f Red: "},{"selector":"@e[tag=rtbeds]"},{"text":"\n§9B§r§f Blue: "},{"selector":"@e[tag=btbeds]"},{"text":"\n§eY§r§f Yellow: "},{"selector":"@e[tag=ytbeds]"},{"text":"\n§aG§r§f Green: "},{"selector":"@e[tag=gtbeds]"},{"text":"§7\n\n§fYou are now a viewer\n\n§emc.163.com/cnpixel"}]}


#纯场外 交给lobby
execute as @a[tag=!inf,tag=!观战] run function showbar/lobby




