# -*- coding: utf-8 -*-
# @Author : Joyful233
# @Function : show lobby scoreboard

#中
execute if score start B7O14L = num_-1 B7O14L run execute as @a[tag=语言] at @s run titleraw @s actionbar {"rawtext":[{"text":"     §e§l起床战争§r\n"},{"text":"§726/3/3 v1.66[Beta]\n\n§f等级:§7 "},{"score":{"objective":"G7C23S","name":"@s"}},{"text":"✿\n\n§f进度: §b "},{"score":{"name":"@s","objective":"E1B36G"}},{"text":"§7/§a5k\n"},{"translate":"  §7[§b%%1§7%%2]  ","with":{"rawtext":[{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■"},{"text":"■■"},{"text":"■■■"},{"text":"■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■■■"}]}}]}},{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■"},{"text":"■■■"},{"text":"■■"},{"text":"■"},{"text":""}]}}]}}]}},{"text":"\n\n§f代币: §2"},{"score":{"objective":"Q0A59I","name":"@s"}},{"text":"\n\n§f总击杀:§a "},{"score":{"objective":"V5G28k","name":"@s"}},{"text":"\n§f总胜场:§a "},{"score":{"objective":"T8R43H","name":"@s"}},{"text":"\n\n§b§l打扫战场中\n对局在稍后开始\n\n§r§emc.163.com/cnpixel"}]}

#英
execute if score start B7O14L = num_-1 B7O14L run execute as @a[tag=language] at @s run titleraw @s actionbar {"rawtext":[{"text":"     §e§lBED WARS§r\n"},{"text":"§726/3/3 v1.66[Beta]\n\n§fLevel:§7 "},{"score":{"objective":"G7C23S","name":"@s"}},{"text":"✿\n\n§fProgress: §b "},{"score":{"name":"@s","objective":"E1B36G"}},{"text":"§7/§a5k\n"},{"translate":"  §7[§b%%1§7%%2]  ","with":{"rawtext":[{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■"},{"text":"■■"},{"text":"■■■"},{"text":"■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■■■"}]}}]}},{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■"},{"text":"■■■"},{"text":"■■"},{"text":"■"},{"text":""}]}}]}}]}},{"text":"\n\n§fTokens: §2"},{"score":{"objective":"Q0A59I","name":"@s"}},{"text":"\n\n§fTotal Kills: §a"},{"score":{"objective":"V5G28k","name":"@s"}},{"text":"\n§fTotal Wins: §a"},{"score":{"objective":"T8R43H","name":"@s"}},{"text":"\n\n§b§lReloading..\nPlease waiting\n\n§r§emc.163.com/cnpixel"}]}



#中
execute if score start B7O14L = num_0 B7O14L run execute as @a[tag=语言] run titleraw @s actionbar {"rawtext":[{"text":"      §e§l起床战争§r\n"},{"text":"§726/3/3 v1.66[Beta]\n\n§f等级:§7 "},{"score":{"objective":"G7C23S","name":"@s"}},{"text":"✿\n\n§f进度: §b "},{"score":{"name":"@s","objective":"E1B36G"}},{"text":"§7/§a5k\n"},{"translate":"  §7[§b%%1§7%%2]  ","with":{"rawtext":[{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■"},{"text":"■■"},{"text":"■■■"},{"text":"■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■■■"}]}}]}},{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■"},{"text":"■■■"},{"text":"■■"},{"text":"■"},{"text":""}]}}]}}]}},{"text":"\n\n§f代币: §2"},{"score":{"objective":"Q0A59I","name":"@s"}},{"text":"\n\n§f总击杀:§a "},{"score":{"objective":"V5G28k","name":"@s"}},{"text":"\n§f总胜场:§a "},{"score":{"objective":"T8R43H","name":"@s"}},{"text":"\n\n§emc.163.com/cnpixel"}]}

#英
execute if score start B7O14L = num_0 B7O14L run execute as @a[tag=language] run titleraw @s actionbar {"rawtext":[{"text":"     §e§lBED WARS§r\n"},{"text":"§726/3/3 v1.66[Beta]\n\n§fLevel:§7 "},{"score":{"objective":"G7C23S","name":"@s"}},{"text":"✿\n\n§fProgress: §b "},{"score":{"name":"@s","objective":"E1B36G"}},{"text":"§7/§a5k\n"},{"translate":"  §7[§b%%1§7%%2]  ","with":{"rawtext":[{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■"},{"text":"■■"},{"text":"■■■"},{"text":"■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■■■"}]}}]}},{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■"},{"text":"■■■"},{"text":"■■"},{"text":"■"},{"text":""}]}}]}}]}},{"text":"\n\n§fTokens: §2"},{"score":{"objective":"Q0A59I","name":"@s"}},{"text":"\n\n§fTotal Kills: §a"},{"score":{"objective":"V5G28k","name":"@s"}},{"text":"\n§fTotal Wins: §a"},{"score":{"objective":"T8R43H","name":"@s"}},{"text":"\n\n§emc.163.com/cnpixel"}]}


#中
execute if score start B7O14L = num_2 B7O14L run execute as @a[tag=语言,tag=!inf,tag=!观战] run titleraw @s actionbar {"rawtext":[{"text":"       §e§l起床战争§r\n"},{"text":"§726/3/3 v1.66[Beta]\n\n§f等级:§7 "},{"score":{"objective":"G7C23S","name":"@s"}},{"text":"✿\n\n§f进度: §b "},{"score":{"name":"@s","objective":"E1B36G"}},{"text":"§7/§a5k\n"},{"translate":"  §7[§b%%1§7%%2]  ","with":{"rawtext":[{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■"},{"text":"■■"},{"text":"■■■"},{"text":"■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■■■"}]}}]}},{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■"},{"text":"■■■"},{"text":"■■"},{"text":"■"},{"text":""}]}}]}}]}},{"text":"\n\n§f代币: §2"},{"score":{"objective":"Q0A59I","name":"@s"}},{"text":"\n\n§f总击杀:§a "},{"score":{"objective":"V5G28k","name":"@s"}},{"text":"\n§f总胜场:§a "},{"score":{"objective":"T8R43H","name":"@s"}},{"text":"\n\n§a§l游戏进行中,可前往观战\n耐心等待下一局\n\n§r§emc.163.com/cnpixel"}]}

#英
execute if score start B7O14L = num_2 B7O14L run execute as @a[tag=language,tag=!inf,tag=!观战] run titleraw @s actionbar {"rawtext":[{"text":"     §e§lBED WARS§r\n"},{"text":"§726/3/3 v1.66[Beta]\n\n§fLevel:§7 "},{"score":{"objective":"G7C23S","name":"@s"}},{"text":"✿\n\n§fProgress: §b "},{"score":{"name":"@s","objective":"E1B36G"}},{"text":"§7/§a5k\n"},{"translate":"  §7[§b%%1§7%%2]  ","with":{"rawtext":[{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■"},{"text":"■■"},{"text":"■■■"},{"text":"■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■■■"}]}}]}},{"translate":"%%2","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..2500}]"},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..500}]"},{"selector":"@s[scores={E1B36G=..1000}]"},{"selector":"@s[scores={E1B36G=..1500}]"},{"selector":"@s[scores={E1B36G=..2000}]"},{"selector":"@s[scores={E1B36G=..2500}]"},{"text":"■■■■■■■■■"},{"text":"■■■■■■■■"},{"text":"■■■■■■■"},{"text":"■■■■■■"},{"text":"■■■■■"}]}},{"translate":"%%6","with":{"rawtext":[{"selector":"@s[scores={E1B36G=..3000}]"},{"selector":"@s[scores={E1B36G=..3500}]"},{"selector":"@s[scores={E1B36G=..4000}]"},{"selector":"@s[scores={E1B36G=..4500}]"},{"selector":"@s[scores={E1B36G=..5000}]"},{"text":"■■■■"},{"text":"■■■"},{"text":"■■"},{"text":"■"},{"text":""}]}}]}}]}},{"text":"\n\n§fTokens: §2"},{"score":{"objective":"Q0A59I","name":"@s"}},{"text":"\n\n§fTotal Kills: §a"},{"score":{"objective":"V5G28k","name":"@s"}},{"text":"\n§fTotal Wins: §a"},{"score":{"objective":"T8R43H","name":"@s"}},{"text":"\n\n§a§lIs Gameing..\nYou can viewing it\n\n§r§emc.163.com/cnpixel"}]}





